/**
 * EXAMES_LIST_EXPORT
 * Dados estáticos consolidados para o catálogo de exames.
 */
export const EXAMES_LIST_EXPORT = [
    { "idx": 0, "id": 13, "nome": "Avaliação Clínica" },
    { "idx": 1, "id": 448, "nome": "Audiometria" },
    { "idx": 2, "id": 449, "nome": "Acuidade Visual" },
    { "idx": 3, "id": 450, "nome": "Espirometria" },
    { "idx": 4, "id": 451, "nome": "Eletrocardiograma" },
    { "idx": 5, "id": 452, "nome": "Eletroencefalograma" },
    { "idx": 6, "id": 453, "nome": "Raio-X Tórax PA OIT" },
    { "idx": 7, "id": 454, "nome": "Raio-X Coluna L-Sacra" },
    { "idx": 8, "id": 455, "nome": "Raio-X Mãos e Braços" },
    { "idx": 9, "id": 456, "nome": "Raio-X Punho" },
    { "idx": 10, "id": 457, "nome": "Hemograma Completo" },
    { "idx": 11, "id": 458, "nome": "Glicemia em Jejum" },
    { "idx": 12, "id": 459, "nome": "EPF (parasitológico fezes)" },
    { "idx": 13, "id": 460, "nome": "EAS (urina)" },
    { "idx": 14, "id": 461, "nome": "Grupo Sanguíneo + Fator RH" },
    { "idx": 15, "id": 462, "nome": "Gama GT" },
    { "idx": 16, "id": 463, "nome": "TGO / TGP" },
    { "idx": 17, "id": 464, "nome": "Ácido Trans. Muconico" },
    { "idx": 18, "id": 465, "nome": "Ácido Úrico" },
    { "idx": 19, "id": 466, "nome": "Ácido Hipúr. (Tolueno urina)" },
    { "idx": 20, "id": 467, "nome": "Ácido Metil Hipúrico" },
    { "idx": 21, "id": 468, "nome": "Ácido Mandélico" },
    { "idx": 22, "id": 469, "nome": "ALA-U" },
    { "idx": 23, "id": 470, "nome": "Hemoglobina glicada" },
    { "idx": 24, "id": 471, "nome": "Coprocultura" },
    { "idx": 25, "id": 472, "nome": "Colesterol T e F" },
    { "idx": 26, "id": 473, "nome": "Chumbo Sérico" },
    { "idx": 27, "id": 474, "nome": "Creatinina" },
    { "idx": 28, "id": 475, "nome": "Ferro Sérico" },
    { "idx": 29, "id": 476, "nome": "Manganês Urinário" },
    { "idx": 30, "id": 477, "nome": "Manganês Sanguíneo" },
    { "idx": 31, "id": 478, "nome": "Reticulócitos" },
    { "idx": 32, "id": 479, "nome": "Triglicerídeos" },
    { "idx": 33, "id": 480, "nome": "IGE Específica - Abelha" },
    { "idx": 34, "id": 481, "nome": "Acetona Urinária" },
    { "idx": 35, "id": 482, "nome": "Anti HAV" },
    { "idx": 36, "id": 483, "nome": "Anti HBS" },
    { "idx": 37, "id": 484, "nome": "Anti HBSAG" },
    { "idx": 38, "id": 485, "nome": "Anti HCV" },
    { "idx": 39, "id": 486, "nome": "Carboxihemoglobina" },
    { "idx": 40, "id": 487, "nome": "Exame Toxicológico Pelo" },
    { "idx": 41, "id": 488, "nome": "Avaliação Vocal" },
    { "idx": 42, "id": 489, "nome": "Avaliação Psicossocial" },
    { "idx": 43, "id": 490, "nome": "Avaliação Psicológica" },
    { "idx": 44, "id": 491, "nome": "Aspecto da Pele" },
    { "idx": 45, "id": 492, "nome": "Questionário Epilepsia" },
    { "idx": 46, "id": 493, "nome": "Teste Palográfico" },
    { "idx": 47, "id": 494, "nome": "Teste de Atenção" },
    { "idx": 48, "id": 495, "nome": "Teste Romberg" },
    { "idx": 49, "id": 496, "nome": "Exame Toxicológico Urina" },
    { "idx": 50, "id": 497, "nome": "Higidez" },
    { "idx": 51, "id": 498, "nome": "Grupo Sanguíneo" },
    { "idx": 52, "id": 212, "nome": "Exame de Epworth" }
];

